### PR TITLE
adding creation of selenium data folder to deployment

### PR DESCRIPTION
**Pull request by tkalir**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@OriHoch can you please review this pr?

**Review by OriHoch — CHANGES_REQUESTED** [review]
why do you need to run this command on each deployment? doesn't it just need to run once? you can just ssh to the server and run it

**Comment by tkalir** [comment]
@OriHoch the permissions reset back to default after we reboot the instance
 
image

**Comment by atalyaalon** [comment]
@tkalir Thanks, this is indeed a problem that permissions are reset back to default after rebooting.
Merging 
Thanks @OriHoch !

**Comment by tkalir** [comment]
hi @OriHoch 
the workflow had a problem running after this commit, and even after we removed the the call to bin/apps.py create_selenium_data_folder it still doesn't work.

`/home/runner/work/_temp/fe344642-4bc0-466f-b189-3e65f3f5a47a.sh: line 15: bin/apps.py: Permission denied`

https://github.com/data-for-change/dfc-iac/actions/runs/12233626737/job/34122649887

do you think it's related to the change?
thanks

**Comment by OriHoch** [comment]
@tkalir yes, you removed the execute permission
need to run:

```
chmod +x bin/apps.py
```

then commit it again

**Pull request merged**
